require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  DisplayStyleGuide: true
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "spec/rails_helper.rb"
    - "vendor/**/*"
    - "app/assets/**/*"
    - "log/*"
    - "tmp/*"

Bundler/OrderedGems:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 40

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 500

Style/BlockComments:
  Enabled: false

# Apparently, this rule is supposed to make us write in English, but all it’s
# doing is depriving the world of beautiful typography, e.g. proper apostrophes,
# ellipsis, etc. If Rubocop wants to enforce that we’re writing in English, they
# better come up with some fancy AI approach ;)
Style/AsciiComments:
  Enabled: false

# Top-level module docs are turned off by default, but e.g. app/models has it turned on locally
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Style/ClassAndModuleChildren:
  Enabled: false
